config/routes.rb
Rails.application.routes.draw do
    root to: 'tasks#index'
    get 'tasks', to: 'tasks#index'
    get 'tasks/new', to: 'tasks#new' # get the form to create a new task
    get 'tasks/:id', to: 'tasks#show', as: 'task' # set alias for this
    post 'tasks', to: 'tasks#create' # post a new task
    get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task' # get the form to edit an existing task
    patch 'tasks/:id', to: 'tasks#update' # update an existing task
    delete 'tasks/:id', to: 'tasks#destroy' # delete an existing task

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @task = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

 <%= link_to 'Cancel', tasks_path %>

app/views/tasks/index.html.erb
<h1>All Tasks:</h1>
  <ul>
    <% @task.each do |task| %>
      <li><%= task.name %></li>
      <%= link_to 'Show task', task_path(task) %> <%# () gets id of task - params? %>
    <% end %>
  </ul>

  <%= link_to 'Add task', tasks_new_path %>  <%# rake routes to get the prefixes before _path %>

app/views/tasks/new.html.erb
<!-- <form action="/tasks" method="post">
  <label for="name">Name: </label>
  <input type="text" name="task[name]" id="name">
  <input type="submit">
</form> -->
<h1>Add task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

 <%= link_to 'Cancel', tasks_path %>

app/views/tasks/show.html.erb
<h1>Task</h1>
<h2><%= @task.name %></h2>
<p>Stop being lazy and do this!</p>
<%# need @ in () %>
<%= link_to 'Delete', task_path(@task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<%= link_to 'Edit', edit_task_path(@task) %>
<%= link_to 'Back to all tasks', tasks_path %>